# Generated by Django 6.0.4 on 2026-04-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
    ]
